name: Update Derafsh Configs

on:
  schedule:
    - cron: '0 0 * * *' # هر 4 ساعت یکبار (ساعت 0, 4, 8, 12...)
  workflow_dispatch: # اجازه میده دکمه Run رو دستی هم بزنی

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # اجازه میده فایل رو تغییر بده و ذخیره کنه

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Collector Script
        run: python collector.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "Derafsh Bot"
          git config --global user.email "bot@derafsh.com"
          git add derafsh_servers.txt
          git commit -m "🔄 Auto-update configs" || echo "No changes to commit"
          git push
